### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@isuruf, would you be willing to merge this one to add me?  I had to do some clean-up to even get the current version of the package to build...

**Comment by isuruf** [comment]
Thanks @xylar for agreeing to be a maintainer

**Comment by xylar** [comment]
@isuruf, thanks a bunch!

**Pull request merged**
