### PR TITLE
Remove exceptiongroup_dev label

### PR DESCRIPTION
**Pull request by xylar**
We can now use the release candidate from the main label

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
See https://github.com/conda-forge/exceptiongroup-feedstock/pull/8#issuecomment-1226249591 for a bit of background on why it's okay to put the `exceptiongroup` release candidate packages on the `main` label.  Long story short, if there hasn't been a release yet, it's allowed.

**Comment by xylar** [comment]
@Tinche and @agronholm, I just wanted to make you aware that I'm finally resolving the issue we discussed in https://github.com/conda-forge/cattrs-feedstock/pull/19.  Sorry for causing unnecessary trouble.  I learned a lot today about when it's fine to have a pre-release package on the `main` label on conda-forge.

**Comment by xylar** [comment]
@JWCook, you may now want to update your build in https://github.com/conda-forge/requests-cache-feedstock/pull/35 to include this latest `cattrs`.  Sorry for the delay.

**Comment by JWCook** [comment]
> Long story short, if there hasn't been a release yet, it's allowed.

Well, I learned something new today. Thanks for following up on this!

**Pull request merged**
