### PR TITLE
Update recipe to `v22.1.0`

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) `NA`
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
## Reason for Build Failure: `1/N`

`Observation`:

> :point_right: *Complains and fails despite having `poetry-core` in run-requirements.*

- `line number: 75`: [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=536865&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=75)
- `time elapsed`: `1m:20s`

```sh
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested poetry-core >=1.1.0
```

Fix: change `1.1.0` to `1.1.0b3`

**Comment by sugatoray** [comment]
Hi @xylar @Tinche @aldanor 

👉 This PR updates the recipe with the latest versions of the dependencies (e.g. poetry-core: `v1.1.0b3`, released on 12-Jul-2022).

I only realized that there is another PR (#19) (a few months old) that was worked on earlier to update `cattrs` to `v22.1.0`, after pushing this PR. I am the maintainer of `bentoml`, which depends on `cattrs`. 

I was not able to move forward with updating `bentoml` as the cattrs `v22.1.0` was not available on conda-forge. So, ended up pushing this PR (with the latest version of poetry-core: `v1.1.0b3`, released on 12-Jul-2022).

I would also like to add myself as a maintainer of `cattrs`. If you kindly approve of this PR and merge it, it will be very helpful.

- https://github.com/conda-forge/bentoml-feedstock/pull/4

Thank you.

Closes #19

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sugatoray, this looks good to me.  I'll merge as soon as the rerender adds you as a maintainer (or does nothing).

**Pull request merged**
